[R20-1775] Map sidepanel
dpc-sdp/ripple-framework pull request #1097
Opened 2024-03-27 00:13 UTC by jeffdowdle

**Issue**:

### What I did

- 
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-04-04 05:10 UTC, jeffdowdle commented on packages/ripple-tide-search/composables/useTideSearch.ts
Most of the changes to this file are to support "Dynamic aggregations" i.e. result counts displayed next to each filter option that update base of the current search results.

![Screenshot 2024-04-04 at 3 51 42 pm](https://github.com/dpc-sdp/ripple-framework/assets/5309152/e8ba4b2f-11e2-4a6e-b287-f21d972984f7)

This wasn't trivial to do and requires running a seperate search everytime a search is done. This separate search needs to send a similar but slightly different query DSL to behave the way people would expect.

Firstly, to turn of this feature, there is an option called `dynamicAggregations`
```
{
  searchListingConfig: {
     dynamicAggregations: true
  }
}
```

This will show dynamic result counts, but will produce bad results because filters will filter themselves out. For example, selecting an option in a dropdown will cause all other options to display "(0)" as their count.

To fix this, you need to exclude certain filters from being sent to the seperate aggregations request, to do this you set `excludeFromAggregations` to `true` in a user filter config item:

![Screenshot 2024-04-04 at 4 01 09 pm](https://github.com/dpc-sdp/ripple-framework/assets/5309152/15200b21-8cf3-4fbe-87a5-2f222689d2d3)

2024-04-04 05:10 UTC, jeffdowdle commented on packages/ripple-tide-search/server/api/tide/elasticsearch/[...].ts
> +    on: {
This adds support needed for elasticsearch instances that require basic auth

2024-04-04 05:10 UTC, jeffdowdle commented on packages/ripple-ui-maps/src/components/map/RplMap.vue
> +      const pinTitle = point.features.length
Fixes the pin title being 'undefined' if the search result doesn't have a 'title' property, instead it will get the pin title based on the titleObjPath in the search config in the same way that the popup does

2024-04-16 22:59 UTC, jeffdowdle commented on packages/ripple-test-utils/step_definitions/components/maps.ts
> +    set(response, 'bodyComponents[0].props.mapConfig.sidePanel.enabled', true)
Often we want to just change one thing in and test that, but previously we had to create a new json file for even a tiny change, instead we can intercept the fixture to change a specific part of the json, this ends up more readable in the `.feature` file too as `Given the side panel is enabled`

2024-04-18 06:31 UTC, lambry commented on examples/nuxt-app/test/features/maps/__image_snapshots__/map-popup-type-popover-with-sidepanel #0.png
@jeffdowdle This is just being picky, but could all the test titles display the first item in the array, just to look a bit more realistic? (also, I like the tiles)

2024-04-18 07:04 UTC, waitingallday commented on examples/nuxt-app/test/features/maps/__image_snapshots__/map-popup-type-popover-with-sidepanel #0.png
Or is it just a fixture problem? (did the mapping change from an array to a string at some point?)

2024-04-18 23:34 UTC, dylankelly requested changes
as Davids comments - lets just fix up the title formatting in the tests. But great work on this

2024-04-19 01:39 UTC, dylankelly approved these changes

2024-04-19 01:39 UTC, merged