fix(@dpc-sdp/nuxt-ripple): fix console error on route change
dpc-sdp/ripple-framework pull request #1152
Opened 2024-05-06 23:52 UTC by lambry

### What I did

- Quick fix for console errors on all route changes with social share sidebar

<img width="495" alt="Screenshot 2024-05-06 at 5 19 11 PM" src="https://github.com/dpc-sdp/ripple-framework/assets/287178/c904bebd-81b7-438d-8a0d-7e7559b6a8d3">

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-05-06 23:53 UTC, dylankelly approved these changes

2024-05-07 00:08 UTC, dylankelly requested changes
maybe try without the vue version of useRoute

2024-05-07 00:32 UTC, lambry commented
> maybe try without the vue version of useRoute

Hey @dylankelly, that's using the Nuxt version (useRoute) instead now, cheers.

2024-05-07 04:13 UTC, dylankelly approved these changes

2024-05-07 05:25 UTC, waitingallday approved these changes

2024-05-08 00:14 UTC, merged