[R20-1987] Changed visited link style to a util class
dpc-sdp/ripple-framework pull request #1221
Opened 2024-06-14 00:30 UTC by jeffdowdle

**Issue**: https://digital-vic.atlassian.net/browse/R20-1987

### What I did

- 
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-06-16 23:49 UTC, dylankelly requested changes

2024-06-16 23:49 UTC, dylankelly commented on packages/ripple-ui-core/src/styles/utilities/_visited.css
> +.rpl-u-visited {
can we call this `rpl-u-link-visited` instead? a bit more verbose, but better readability

2024-06-17 23:48 UTC, waitingallday approved these changes

2024-06-17 23:48 UTC, lambry approved these changes

2024-06-20 00:07 UTC, dylankelly approved these changes

2024-06-20 00:10 UTC, merged