[R20-1969] add skeletons to site search
dpc-sdp/ripple-framework pull request #1233
Opened 2024-06-21 02:04 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-1969

### What I did

- Update site search to bring it inline with search listings/custom collections. i.e. add skeleton loader, scroll to results.

https://github.com/dpc-sdp/ripple-framework/assets/287178/5da9df39-3216-4f5c-a47f-2ad5ffb90718

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-06-21 02:05 UTC, waitingallday approved these changes

2024-06-23 23:59 UTC, jeffdowdle approved these changes

2024-06-24 00:01 UTC, dylankelly requested changes

2024-06-24 00:01 UTC, dylankelly commented on packages/ripple-tide-search/components/global/TideCustomCollection.vue
> +      scrollToResults(resultsContainer.value, 16)
can you give this magic number a var name to describe it?

2024-06-24 01:56 UTC, lambry commented on packages/ripple-tide-search/components/global/TideCustomCollection.vue
> +      scrollToResults(resultsContainer.value, 16)
Hey @dylankelly, that's done. Cheers

2024-06-24 01:58 UTC, lambry commented on packages/ripple-tide-search/components/global/TideSearchResultsList.vue
> +  <component :is="loading ? 'div' : 'section'">
This seemed to be the only sure fire way to avoid the loading issue (in cypress). If the root element changes the merged dynamic component issue doesn't occur.

2024-06-24 02:31 UTC, dylankelly commented on packages/ripple-tide-search/components/global/TideSearchResultsList.vue
> +  <component :is="loading ? 'div' : 'section'">
can you add a comment in code here please? No way someone will figure that out in the future.

2024-06-26 04:19 UTC, dylankelly approved these changes

2024-06-26 04:22 UTC, merged