[R20-1433] improve accuracy of more count for dropdowns
dpc-sdp/ripple-framework pull request #1240
Opened 2024-06-27 23:45 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-1433

### What I did

- Improve accuracy of more count for dropdowns, this mostly just ensures it doesn't display `+1 more` when there's actually 2 and bit hidden.

https://github.com/dpc-sdp/ripple-framework/assets/287178/38fc4aab-f0a8-4d23-8933-7be769869e1f

https://github.com/dpc-sdp/ripple-framework/assets/287178/6d64893e-5509-43dd-bfc2-3cb70bd18e59

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-06-28 00:03 UTC, dylankelly approved these changes

2024-06-28 00:03 UTC, jeffdowdle approved these changes

2024-06-28 00:04 UTC, dylankelly requested changes
Amazing work on this - can we add some Cypress component tests

2024-07-01 00:00 UTC, dylankelly approved these changes

2024-07-01 00:03 UTC, merged