[R20-1985] add custom content rating text
dpc-sdp/ripple-framework pull request #1250
Opened 2024-07-04 23:38 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-1985

### What I did

- Add custom content rating text

**PENDING**: Backend release https://digital-vic.atlassian.net/browse/SDPAP-9240

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [x] I have added cypress tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-07-15 00:08 UTC, dylankelly requested changes

2024-07-15 00:08 UTC, dylankelly commented on packages/nuxt-ripple/mapping/site/index.ts
> +      return getBodyFromField(src, 'field_additional_comment')
Can we detect whether the `field_additional_comment` field is set and if not return the default html?

2024-07-24 00:18 UTC, dylankelly approved these changes

2024-07-24 00:18 UTC, waitingallday approved these changes

2024-07-25 00:03 UTC, merged