[SD-207] Accordion slots
dpc-sdp/ripple-framework pull request #1327
Opened 2024-09-16 07:09 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/SD-207

### What I did

- Support the use of slots in accordions, using the `RplAccordionItem` child wrapper e.g.
```
  <RplAccordion id="accordion1">
    <RplAccordionItem id="item1">
      <template #title>
        Title content here
      </template>
      Body content here
    </RplAccordionItem>
    <RplAccordionItem id="item2" :active="true">
      <template #title>
        Title content here
      </template>
      Body content here
    </RplAccordionItem>
  </RplAccordion>
```

### How to test

- Storybook
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-09-17 06:31 UTC, lambry commented on packages/ripple-ui-core/src/components/accordion/RplAccordion.vue
> +const sharedActiveItems = ref(initialActiveIndexes.value)
Works a treat, just wondering what `sharedActiveItems` is up to here. I'm probably missing something but could `initialActiveIndexes` be `activeIndexes` and `sharedActiveItems` removed? Cheers

2024-09-17 06:53 UTC, waitingallday commented on packages/ripple-ui-core/src/components/accordion/RplAccordion.vue
> +const sharedActiveItems = ref(initialActiveIndexes.value)
I was trying to keep it compatible with `useExpandableState` since it's used in a couple of other places - I tidied it up here though

2024-09-23 03:02 UTC, lambry approved these changes

2024-09-24 00:09 UTC, dylankelly requested changes

2024-09-24 00:09 UTC, dylankelly commented on packages/ripple-ui-core/src/components/accordion/RplAccordion.vue
> +      <slot />
maybe put the items via props in the default slot - so that child components override the props one

2024-09-24 00:10 UTC, dylankelly commented
Would be great to add cypress component test for both props and slot interfaces

2024-09-26 05:25 UTC, waitingallday commented
Merging this now to get in the release, will followup to add the cypress component test separately

2024-09-26 05:25 UTC, merged