[SD-314] Breadcrumbs enhancement
dpc-sdp/ripple-framework pull request #1329
Opened 2024-09-17 04:29 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/SD-314

### What I did

- Team navigation proof of concept from sprint break
- 

### How to test

- https://624ac117357335003a84dac3-acpnqqghmd.chromatic.com/?path=/story/core-navigation-breadcrumbs--example-many-links
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-09-17 06:43 UTC, lambry commented on packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.vue
> +            url=""
Hey, can this be a button (then we won't need the url) with an aria-label? Cheers

2024-09-17 06:57 UTC, waitingallday commented on packages/ripple-ui-core/src/components/breadcrumbs/RplBreadcrumbs.vue
> +            url=""
Oh yeah, good pick up!

2024-09-17 07:02 UTC, lambry approved these changes

2024-09-23 23:35 UTC, jeffdowdle approved these changes

2024-09-24 00:00 UTC, dylankelly requested changes
CAn we put all of this behind a feature flag pls?

2024-09-25 06:49 UTC, dylankelly approved these changes

2024-09-25 06:54 UTC, merged