[SRM-1608] add function to remove new lines
dpc-sdp/ripple-framework pull request #1355
Opened 2024-10-21 22:33 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/SRM-1608

### What I did

- Add a function to remove 'new lines' added via the CMS, these 'new lines' aren't shown on the frontend and cause hydration mismatch errors.

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed
- [ ] I've updated the documentation site as needed
- [x] I have added tests to cover my changes (if not applicable, please state why in a comment)

#### For new UI components only

- [ ] I have added a storybook story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] I have added cypress component tests (if the component is interactive)
- [ ] Any events are emitted on the event bus using `emitRplEvent`

2024-10-21 22:59 UTC, dylankelly requested changes

2024-10-21 22:59 UTC, dylankelly commented on packages/nuxt-ripple/mapping/site/index.ts
> +      return stripNewLines(src?.field_acknowledgement_to_country)
Feel like this should be called getPlainText or something to match its usage like getBody does

2024-10-21 23:56 UTC, lambry commented on packages/nuxt-ripple/mapping/site/index.ts
> +      return stripNewLines(src?.field_acknowledgement_to_country)
Thanks @dylankelly, that's renamed to `getPlainText` now.

2024-10-21 23:59 UTC, dylankelly approved these changes

2024-10-22 23:13 UTC, dylankelly approved these changes

2024-10-22 23:13 UTC, merged