[R20-85] - WIP Primary nav
dpc-sdp/ripple-framework pull request #236
Opened 2022-09-20 05:54 UTC by ChrisCampbellCodes

**Issue**: https://digital-vic.atlassian.net/browse/R20-85

### What I did:
- Added new `rpl-primary-nav` component
- Refactored 'expandable collection' composable to work off IDs rather than index numbers so that it can be used for multi level content, e.g. no colliding indexs of 0
- Removed early POC `nav-primary` component

## Remaining to do:
- Fix mega menu / search dissapearing before nav closing animation has finished
- Investigate / fix tabbing order in mega nav columns
- Add functionality for nav to show / hide based on page scroll direction
- Add sliding animation to mobile mega nav when changing between columns

2022-09-30 05:59 UTC, lambry commented
@ChrisCampbellCodes It's looking good! 

One thing occurs to me, as the menus aren't nested we lose some default functionality in regards to accessibility, i.e. tabbing into and out of menus.

2022-09-30 06:01 UTC, ChrisCampbellCodes commented
> @ChrisCampbellCodes It's looking good!
> 
> One thing occurs to me, as the menus aren't nested we lose some default functionality in regards to accessibility, i.e. tabbing into and out of menus.

ahhh yep that's a good point!

2022-10-10 02:36 UTC, dylankelly requested changes
I can help get that test working, yell out if you want a hand

2022-10-10 02:36 UTC, dylankelly commented on examples/nuxt-app/test/features/site/theme.feature
> +    # Then the site header background color should be "rgb(128, 0, 128)"
This should still work though yeah? Is it just the selector is wrong?

2022-10-10 02:36 UTC, dylankelly commented on examples/nuxt-app/test/features/site/theme.ts
> +//     cy.get(`.rpl-primary-nav`).should('have.css', 'background-color', colour)
Can we reinstate this step definition and update the `cy.get` selector?

2022-10-10 02:36 UTC, dylankelly commented on packages/ripple-ui-core/src/components/layout/layout.stories.mdx
> +        <RplPrimaryNav
👍

2022-10-10 02:36 UTC, dylankelly commented on packages/ripple-ui-core/src/components/layout/layout.stories.mdx
> +        <RplPrimaryNav
@ChrisCampbellCodes can we remove the margin on the layout header div here https://github.com/dpc-sdp/ripple-framework/blob/develop/packages/ripple-ui-core/src/components/layout/layout.css#L42 in this PR? As we discussed, its better for the primary nav component to look after it.

2022-10-10 05:42 UTC, dylankelly approved these changes

2022-10-10 05:43 UTC, dylankelly commented
@ChrisCampbellCodes Tests passing looking goooood! Can we merge it?

2022-10-10 05:52 UTC, lambry approved these changes

2022-10-10 05:53 UTC, merged

2022-10-10 05:53 UTC, lambry commented
Hey @Chris, one minor thing, I noticed the quick exit button isn't on desktop.