feat(@dpc-sdp/ripple-ui-core): add campaign banner component
dpc-sdp/ripple-framework pull request #258
Opened 2022-10-09 22:21 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-88

### What I did

- Adding campaign banners, i.e. primary/featured and secondary/inline

Note: the media/video embed option is to come, it can be added when that component is through design

### How to test

- See Storybook -> WIP -> Campaign banners

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [x] I have added a story covering all variants
- [x] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2022-10-09 23:03 UTC, waitingallday submitted a review, later dismissed

2022-10-09 23:09 UTC, ChrisCampbellCodes approved these changes

2022-10-09 23:09 UTC, dylankelly requested changes
@lambry can you add the campaign component to the page template story

2022-10-09 23:10 UTC, ChrisCampbellCodes commented on packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.css
> +    max-width: 100vw;
As discussed might be worth testing this one on a page where content expanding causing the scrollbar to appear / dissapear, this will affect 100vw width on some browsers. Super minor, just wanted to flag it

2022-10-09 23:10 UTC, ChrisCampbellCodes approved these changes

2022-10-10 04:56 UTC, lambry commented
> @lambry can you add the campaign component to the page template story

Hey @dylankelly, the campaign banners have been added to the page layout story now. Cheers

Ref: https://624ac117357335003a84dac3-fzmgzgmqqp.chromatic.com/?path=/story/core-templates--landing-page-content

2022-10-10 07:12 UTC, waitingallday approved these changes

2022-10-10 22:40 UTC, dylankelly approved these changes

2022-10-10 22:40 UTC, dylankelly commented on packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.css
> +  --local-flex-sapcer: var(--rpl-sp-6);
spelling ?

2022-10-10 22:40 UTC, dylankelly commented on packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.css
> +        clip-path: polygon(15% 44%, 100% 0, 100% 100%, 0% 100%);
Neat! TIL

2022-10-10 22:40 UTC, dylankelly commented on packages/ripple-ui-core/src/components/campaign-banner/primary-campaign.stories.mdx
> +      viewports: [bpMin.s, bpMin.l]
👍

2022-10-10 22:41 UTC, lambry commented on packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.css
> +  --local-flex-sapcer: var(--rpl-sp-6);
Ahh noooooo

2022-10-10 23:13 UTC, merged