[R20-142] adding news template
dpc-sdp/ripple-framework pull request #305
Opened 2022-11-17 03:54 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-142

### What I did

- Added news template

![Screenshot 2022-11-17 at 14-52-35 news-template--template](https://user-images.githubusercontent.com/287178/202350914-b689fd88-a6b2-457c-8920-ff478728bc9a.png)

### How to test

- See storybook/reference site

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [x] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2022-11-17 20:39 UTC, jeffdowdle requested changes

2022-11-17 20:39 UTC, jeffdowdle commented on packages/ripple-tide-news/src/components/tide-news-body.vue
> +  <div v-if="details" class="tide-news__details rpl-page-component rpl-content">
Am I right in thinking that classes like `tide-news__details` have been added just so the tests have something to target? If so, a better option would be to use the `data-cy` attribute. 

e.g. `data-cy="news-details"` and then in cypress `cy.get("[data-cy="news-details"]")`

2022-11-17 22:18 UTC, lambry commented on packages/ripple-tide-news/src/components/tide-news-body.vue
> +  <div v-if="details" class="tide-news__details rpl-page-component rpl-content">
Hey @jeffdowdle, it's using data attributes for tests now, I've left the classes in place for the time being as this is the style most other tide components follow, cheers.

2022-11-17 22:54 UTC, dylankelly approved these changes

2022-11-18 01:35 UTC, ChrisCampbellCodes approved these changes

2022-11-18 02:36 UTC, jeffdowdle approved these changes

2022-11-18 02:37 UTC, merged