[R20-379] - Conditional logic for webforms
dpc-sdp/ripple-framework pull request #362
Opened 2023-01-04 21:34 UTC by jeffdowdle

**Issue**:

### What I did

- 
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-01-09 04:51 UTC, dylankelly requested changes
see typo

2023-01-09 04:51 UTC, dylankelly commented on packages/ripple-ui-forms/src/components/RplFormLabel/RplFormLabel.vue
> +  message: 'asd'
this belong here?

2023-01-09 04:51 UTC, dylankelly commented on packages/ripple-tide-landing-page/mapping/page-components/webforms/webform-conditional-logic.ts
> +function convertSelectorToOperand(ruleObject, selector): Operand {
If we're not going to do component tests, are some unit tests here worthwhile?

2023-01-10 23:02 UTC, waitingallday approved these changes

2023-01-10 23:02 UTC, merged