[R20 334, R20-378] Back to top and skip links
dpc-sdp/ripple-framework pull request #379
Opened 2023-01-23 22:02 UTC by jeffdowdle

**Issue**: R20 334, R20-378

### What I did

- Added back to top button to layout
- Added skip links to layout
- Added a story for demoing back to top and skip links

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-01-23 23:04 UTC, waitingallday approved these changes

2023-01-23 23:08 UTC, dylankelly requested changes

2023-01-23 23:08 UTC, dylankelly commented on packages/ripple-ui-core/src/components/layout/back-to-top.vue
> +  return scrollY.value > 1080
Can we make this a variable and document its purpose?

2023-01-24 06:21 UTC, dylankelly approved these changes

2023-01-24 06:21 UTC, merged