[R20-535] Remove duplicate component imports
dpc-sdp/ripple-framework pull request #417
Opened 2023-02-13 07:03 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/R20-535

### What I did

- Create additional vite build for components, update all files to use new endpoint (slight reworking in nuxt, content types, storybook)
- Update all packages to use `workspace:*`

### How to test

- All of the tests
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-02-14 22:12 UTC, dylankelly requested changes
@waitingallday can you change those imports in the nuxt only components to import from `#components` instead of `'@dpc-sdp/ripple-ui-core/vue'`

2023-02-14 22:12 UTC, dylankelly commented on packages/nuxt-ripple/components/TideBaseLayout.vue
> +import { RplChip } from '@dpc-sdp/ripple-ui-core/vue'
import from `#components`

2023-02-14 22:12 UTC, dylankelly commented on packages/nuxt-ripple/components/TideBreadcrumbs.vue
> +import { RplBreadcrumbs } from '@dpc-sdp/ripple-ui-core/vue'
import from `#components`

2023-02-14 22:12 UTC, dylankelly commented on packages/nuxt-ripple/components/TideDynamicComponents.vue
> +import { RplPageComponent, RplCardGrid } from '@dpc-sdp/ripple-ui-core/vue'
import from `#components`

2023-02-14 22:12 UTC, dylankelly commented on packages/nuxt-ripple/components/TideErrorPage.vue
> +import { RplHeaderGraphic, RplErrorMessage } from '@dpc-sdp/ripple-ui-core/vue'
import from `#components`

2023-02-14 22:12 UTC, dylankelly commented on packages/nuxt-ripple/error.vue
> +import { RplHeaderGraphic, RplErrorMessage } from '@dpc-sdp/ripple-ui-core/vue'
import from `#components`

2023-02-15 02:23 UTC, dylankelly approved these changes

2023-02-15 02:58 UTC, jeffdowdle approved these changes

2023-02-15 02:58 UTC, merged