[R20-406] Fix date timezone issue in news content type
dpc-sdp/ripple-framework pull request #427
Opened 2023-02-16 06:34 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/R20-406

### What I did

- Unified `dateFormat` util (there were 3)
- Move news call of `dateFormat` from mapping to sfc - this is what caused the timezone difference on the reference site

### How to test

- Check date on published site
  - https://www.v2.reference.sdp.vic.gov.au/govhack-2022-coming-soon-connections-event-and-hack-weekend-demo

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-02-19 21:56 UTC, dylankelly approved these changes

2023-02-19 21:58 UTC, dylankelly requested changes
You will need to update the Cypress tests for the news content type

2023-02-20 05:32 UTC, lambry approved these changes

2023-02-20 22:21 UTC, dylankelly commented on examples/nuxt-app/test/fixtures/news/sample-news.json
> -    "published": "Friday, 11 November 2022 at 11:11 am",
Should dates be formatted server side? I thought we had agreed that they would be formatted client side?

2023-02-20 22:48 UTC, dylankelly approved these changes

2023-02-20 22:48 UTC, merged