[R20-519] ripple print styles
dpc-sdp/ripple-framework pull request #445
Opened 2023-02-27 21:54 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-519

### What I did

- Adding print styles across the board
- Use teleport for modals
- Add `link` markup plugin
- Note the `inverted` secondary logo would need an extra CMS field

### Screenshot

Before
[print-v2-before.pdf](https://github.com/dpc-sdp/ripple-framework/files/10844637/print-v2-before.pdf)

After
[print-v2-after.pdf](https://github.com/dpc-sdp/ripple-framework/files/10844653/print-v2-after.pdf)

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-02-28 02:50 UTC, dylankelly approved these changes
nice one! You will need to update you step definitions to move them to https://github.com/dpc-sdp/ripple-framework/tree/develop/packages/ripple-test-utils/step_definitions - this is so they can be shared across projects

2023-02-28 02:51 UTC, dylankelly requested changes
un approving so those step definitions get moved

2023-03-01 23:29 UTC, dylankelly approved these changes

2023-03-01 23:29 UTC, waitingallday approved these changes

2023-03-01 23:29 UTC, merged