[R20-456] trail switching to new menu endpoint
dpc-sdp/ripple-framework pull request #484
Opened 2023-03-10 05:28 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-456

### What I did

- Switched over to the new menu endpoint

2023-05-17 06:14 UTC, jeffdowdle requested changes
This is looking really good, my main question is, do you think we need to support both of these with a feature flag at this stage because not all backends will have the new endpoint?

2023-05-17 06:47 UTC, lambry commented
> This is looking really good, my main question is, do you think we need to support both of these with a feature flag at this stage because not all backends will have the new endpoint?

@jeffdowdle Good question, the backend update for this is actually already in a tide release https://github.com/dpc-sdp/tide_api/releases/tag/3.0.10 so it's ahead of the curve there.

2023-05-18 03:30 UTC, lambry commented
> This is looking really good, my main question is, do you think we need to support both of these with a feature flag at this stage because not all backends will have the new endpoint?

Hey @jeffdowdle a 'flag' now exists so the 'single' or 'paginated' endpoint can be used. Here's a screenshot for each running, notice the menu or is different.

## New (Single request)
![single](https://github.com/dpc-sdp/ripple-framework/assets/287178/e5b195db-ec2f-483c-9a68-1342e2155191)

## Old (Paginated request)
![paginated](https://github.com/dpc-sdp/ripple-framework/assets/287178/5e0058b4-31f6-4020-8534-efe55a8f08a9)

2023-05-18 23:54 UTC, dylankelly approved these changes

2023-05-19 00:03 UTC, jeffdowdle commented on packages/ripple-tide-api/src/services/lib/site-menu.ts
> -    if (link.attributes.enabled) {
We should bring back to check, something like 
`if (!IsOldMenuEndpoint || (IsOldMenuEndpoint && link.attributes.enabled) {`

2023-05-19 00:28 UTC, lambry commented on packages/ripple-tide-api/src/services/lib/site-menu.ts
> -    if (link.attributes.enabled) {
Hey, this is done. I've just called it `enabledCheck`.

2023-05-19 00:48 UTC, jeffdowdle approved these changes

2023-05-19 01:30 UTC, lambry commented on packages/ripple-tide-api/src/services/tide-api-base.ts
> +    if (this.tide?.menuEndpoint === 'paginated') {
@jeffdowdle Good idea, that's done now.

2023-05-19 02:05 UTC, merged