[R20-401] Added script to hide dismissed alerts to avoid content flash
dpc-sdp/ripple-framework pull request #498
Opened 2023-03-15 22:29 UTC by jeffdowdle

**Issue**: R20-401

Old:

https://user-images.githubusercontent.com/5309152/225457593-ed5ba545-f72f-4e5a-b3db-df30857830e5.mov

New:

https://user-images.githubusercontent.com/5309152/225457695-13f7aa4d-9e0e-45ee-81b9-a779c978fa96.mov

### What I did

- Added static `alerts-script.js`that is loaded as the first item in the <head> to hide dismissed alerts before they are shown to the user.
- also moved sorting to server side mapping function to avoid content flash
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-03-15 22:31 UTC, jeffdowdle commented on packages/nuxt-ripple/app.vue
> +      src: '/scripts/alerts-script.js'
I think it would be much better to inline this script in a script tag but I couldn't figure out how to do that in Nuxt while still keeping it at the top of the <head>

2023-03-15 22:37 UTC, waitingallday approved these changes
👏

2023-03-15 22:45 UTC, dylankelly requested changes

2023-03-15 22:45 UTC, dylankelly commented on packages/nuxt-ripple/app.vue
> +      src: '/scripts/alerts-script.js'
See the example in the docs here https://nuxt.com/docs/getting-started/seo-meta#usehead
```script: [ { innerHTML: 'console.log(\'Hello world\')' } ]```

2023-03-15 22:45 UTC, dylankelly commented on packages/ripple-ui-core/src/components/alert/RplAlert.vue
> +    console.log(alertRef.value.style.display)
console left in to check if anyones paying attention? 😄

2023-03-17 02:06 UTC, dylankelly approved these changes

2023-03-17 02:49 UTC, merged