[R20-708] Image loading performance
dpc-sdp/ripple-framework pull request #518
Opened 2023-03-30 06:02 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/R20-708

### What I did

- Added ability to implement image provider in `RplImage`
- Implemented `srcset` calculations based on asset dimensions and design treatment

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-04-03 04:52 UTC, dylankelly requested changes
Seems to be working fine for the images I saw, had some comments about the maintainability of it. Happy to chat about it.

2023-04-03 04:52 UTC, dylankelly commented on packages/nuxt-ripple/components/global/RplImg.vue
> +const providerSizes = computed(() => {
Did you consider using the $img service from Nuxt image for this https://image.nuxtjs.org/api/dollarimg ? 

I added some solution direction on the original ticket https://digital-vic.atlassian.net/browse/R20-270.

It seems like it would be better to offload this logic? But it seems to be working fine here, might want to extract it out to a lib function and add some unit tests though.

2023-04-03 04:55 UTC, waitingallday commented on packages/nuxt-ripple/components/global/RplImg.vue
> +const providerSizes = computed(() => {
Yes - I started with $img, but ended up working through the various cases until it didn't seem to need it any more. Can definitely work on making this more modular, it's all pretty much dumped in the nuxt-ripple version at the moment

2023-04-13 07:24 UTC, waitingallday commented
Fixtures will probably need updating for cypress to pass

2023-04-13 07:25 UTC, waitingallday commented
Next steps: rework this to output `<picture>` element blocks instead to make the aspect/treatment versions a bit clearer - at the moment it's (ab)using srcset to do this

2023-05-01 03:21 UTC, waitingallday commented
Getting too stale, will need to recreate this PR

2023-05-01 03:21 UTC, closed without merging