fix(@dpc-sdp/ripple-tide-landing-page): removed double accordion title
dpc-sdp/ripple-framework pull request #556
Opened 2023-04-28 00:44 UTC by jeffdowdle

**Issue**: https://digital-vic.atlassian.net/browse/R20-893

### What I did

- 
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-04-30 23:16 UTC, lambry requested changes
Hey @jeffdowdle, we'll need that title passed to `RplAccordion` for analytics. Cheers

<img width="369" alt="Screenshot 2023-05-01 at 9 14 43 am" src="https://user-images.githubusercontent.com/287178/235380445-5bbb634b-eed9-423c-9cb4-9ea5707e6504.png">

2023-05-01 02:37 UTC, jeffdowdle commented
> Hey @jeffdowdle, we'll need that title passed to `RplAccordion` for analytics. Cheers
> 
> <img alt="Screenshot 2023-05-01 at 9 14 43 am" width="369" src="https://user-images.githubusercontent.com/287178/235380445-5bbb634b-eed9-423c-9cb4-9ea5707e6504.png">

Thanks, added the prop back in

2023-05-01 03:08 UTC, waitingallday approved these changes

2023-05-01 03:57 UTC, lambry approved these changes

2023-05-01 04:15 UTC, merged