docs: add basic guide for creating layers
dpc-sdp/ripple-framework pull request #662
Opened 2023-06-20 06:22 UTC by lambry

### What I did

- Added basic guide for creating layers (page number is 5 to slot in with the `feature/docs-marketing-copy` branch)

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-06-20 07:00 UTC, jeffdowdle requested changes

2023-06-20 07:54 UTC, lambry commented on docs/content/framework/3.guides/5.creating-new-layers.md
> +Nuxt layers are used to encapsulate Ripple functionality, so it can easily be shared and reused across projects, see [key concepts - layers](http://localhost:3000/framework/key-concepts/nuxt-layers)
@jeffdowdle good spot, cheers.

2023-06-20 23:55 UTC, waitingallday approved these changes

2023-06-21 01:54 UTC, dylankelly approved these changes

2023-06-21 01:55 UTC, merged