[R20-1276] Implement 301 redirect
dpc-sdp/ripple-framework pull request #713
Opened 2023-07-14 06:54 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/R20-1276

### What I did

- Add 301 redirect into page data composable (`ripple-tide-api` was correctly responding with a redirect type on the API call, but we weren't actioning it at page render)
- 

### How to test

- Create a redirect in reference site
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-07-14 07:59 UTC, waitingallday commented
Probably needs an integration test

2023-07-16 23:15 UTC, dylankelly requested changes

2023-07-16 23:15 UTC, dylankelly commented on packages/nuxt-ripple/composables/use-tide-page.ts
> +      useRouter().replace(data.value.redirect_url)
Why only 301? We should probably handle 302 too.

Also Nuxt has a helper https://nuxt.com/docs/api/utils/navigate-to for redirects

eg:

```await navigateTo(data.value.redirect_url, { redirectCode: data.value.status_code})```

2023-07-17 23:52 UTC, dylankelly approved these changes

2023-07-17 23:52 UTC, lambry approved these changes

2023-07-18 00:03 UTC, merged