[R20-1300] Add breadcrumbs, page rating
dpc-sdp/ripple-framework pull request #717
Opened 2023-07-19 06:19 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/R20-1300

### What I did

- Added content managed page features
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-07-19 06:25 UTC, jeffdowdle requested changes

2023-07-19 06:25 UTC, jeffdowdle commented on packages/ripple-tide-search/components/TideSearchListingPage.vue
> +const { data: contentPage } = useFetch('/api/tide/page', {
I think we are getting the page and the site twice, this might be a relic from when this was a hardcoded search page. I think we should getting page and site passed down as props which originate from `TideTideSearchListing`

2023-07-19 06:27 UTC, waitingallday commented on packages/ripple-tide-search/components/TideSearchListingPage.vue
> +const { data: contentPage } = useFetch('/api/tide/page', {
Ahh ok - didn't even see that one

2023-07-20 01:45 UTC, jeffdowdle approved these changes

2023-07-20 03:19 UTC, merged