[R20-926] Flatten search userFilter value
dpc-sdp/ripple-framework pull request #752
Opened 2023-08-08 08:12 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/R20-926

### What I did

- Using `RplFormOptionButtons`, FormKit will only return an array but the ES `prefix` query needs a single value and I couldn't find anywhere to transform it between FormKit and searchConfig. This adds a check to flatten the filterVal when needed.
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-08-09 00:14 UTC, dylankelly requested changes

2023-08-09 00:14 UTC, dylankelly commented on packages/ripple-tide-search/composables/useTideSearch.ts
> +          // ES expects a single value
Can we make a new filter type for prefix instead?

2023-08-10 00:10 UTC, dylankelly approved these changes

2023-08-10 00:11 UTC, lambry approved these changes

2023-08-10 00:11 UTC, jeffdowdle approved these changes

2023-08-10 00:43 UTC, merged