[R20-1455] Update 500 template to match platform
dpc-sdp/ripple-framework pull request #801
Opened 2023-08-23 07:29 UTC by waitingallday

**Issue**: https://digital-vic.atlassian.net/browse/R20-1455

### What I did

- Update `nuxt-ripple` error template to match platform error page on 500 status
- Use same cut down CSS as platform error page
- Slightly refactor so that 500 is given priority

### How to test

- Cypress
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-08-24 00:07 UTC, dylankelly requested changes

2023-08-24 00:07 UTC, dylankelly commented on packages/nuxt-ripple/error.vue
> +      <div class="rpl-error-message__body rpl-type-p">
Use the existing Error component here

2023-08-24 06:26 UTC, lambry approved these changes

2023-08-24 23:53 UTC, dylankelly submitted a review, later dismissed

2023-08-24 23:53 UTC, dylankelly commented on packages/nuxt-ripple/error.vue
> +console.log(props.error.stack)
remove this pls

2023-08-25 00:19 UTC, dylankelly approved these changes

2023-08-25 00:53 UTC, merged