feat(@dpc-sdp/ripple-tide-search): column classes, array-ify-ing, fil…
dpc-sdp/ripple-framework pull request #805
Opened 2023-08-24 04:13 UTC by lambry

### What I did

- Allow overriding column classes
- Stop array-ify all all values by default
- Don't push 'empty' values to the URL

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-08-25 00:03 UTC, dylankelly requested changes

2023-08-25 00:03 UTC, dylankelly commented on packages/ripple-tide-search/composables/useTideSearch.ts
> +      if (itm.component === 'TideSearchFilterDropdown') {
maybe make this go from a flag on the filter eg: `it.filter.multiple`

2023-08-25 00:03 UTC, dylankelly commented on packages/ripple-tide-search/composables/useTideSearch.ts
> +      if (itm.component === 'TideSearchFilterDropdown') {
and make multiple be the default

2023-08-25 00:39 UTC, lambry commented on packages/ripple-tide-search/composables/useTideSearch.ts
> +      if (itm.component === 'TideSearchFilterDropdown') {
Hey @dylankelly, this now uses filter.multiple instead with multiple being the default. Cheers

2023-08-27 23:55 UTC, dylankelly approved these changes

2023-08-27 23:55 UTC, waitingallday approved these changes

2023-08-27 23:58 UTC, merged