feat(@dpc-sdp/ripple-ui-core): made search result date label customisable
dpc-sdp/ripple-framework pull request #820
Opened 2023-08-29 23:30 UTC by jeffdowdle

**Issue**: https://digital-vic.atlassian.net/browse/R20-1165

### What I did

- In buying for vic search listing, the 'updated' date is actually the published date.
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-08-29 23:32 UTC, dylankelly approved these changes

2023-08-29 23:43 UTC, waitingallday approved these changes

2023-08-29 23:59 UTC, dylankelly commented on packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
> +      {{ dateLabel }}: {{ updated }}
maybe add the semicolon only if dateLabel is defined

2023-09-03 23:53 UTC, dylankelly requested changes
seee comment

2023-09-06 00:12 UTC, dylankelly approved these changes

2023-09-06 00:16 UTC, merged