[R20-1440] make only title and url 'links'
dpc-sdp/ripple-framework pull request #849
Opened 2023-09-12 05:06 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-1440

### To discuss

A couple of issue were brought up on the above ticket (and in discussion), with the desired outcome to be as follows:
- The mouse pointer should only be shown when hovering over the actual link which is the title (and the text shouldn't be clickable). This would avoid the confusion caused when focusing a result item, then hovering another result and not seeing the wrong URL preview shown 

This change addresses that issue i.e now the title and URL are the only elements that are clickable; having said that I'm not sold this, technically all our cards have the same 'issue'.

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-09-14 00:01 UTC, dylankelly requested changes

2023-09-14 00:01 UTC, dylankelly commented on packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
>        class="rpl-search-result__url rpl-type-p-small rpl-u-screen-only"
this should have `aria-hidden` so its not read by screen readers

2023-09-14 00:01 UTC, dylankelly commented on packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
>        class="rpl-search-result__url rpl-type-p-small rpl-u-screen-only"
And can you comment on the reason for the two links to help our future selves

2023-09-14 23:47 UTC, dylankelly approved these changes

2023-09-15 00:54 UTC, jeffdowdle approved these changes

2023-09-15 00:58 UTC, merged