[R20-1070] Increase unit test coverage
dpc-sdp/ripple-framework pull request #915
Opened 2023-10-26 06:44 UTC by waitingallday

**Issue**:

### What I did

- 
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-01-11 23:14 UTC, dylankelly requested changes

2024-01-11 23:14 UTC, dylankelly commented on packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
> +// export const isRelativeUrl = (str: string): boolean => {
please add this back

2024-01-11 23:14 UTC, dylankelly commented on packages/ripple-tide-api/src/utils/markup-transpiler/index.ts
> +// deprecated
?

2024-01-12 04:59 UTC, dylankelly approved these changes

2024-01-14 21:38 UTC, lambry approved these changes

2024-01-14 21:42 UTC, merged