refactor(@dpc-sdp/nuxt-ripple-cli): :recycle: refactor favicon generator into cli tool
dpc-sdp/ripple-framework pull request #938
Opened 2023-11-17 03:59 UTC by waitingallday

**Issue**:

### What I did

- Refactored hook into command on `nuxt-ripple-cli`
```
pnpm -F nuxt-ripple-cli nuxt-ripple favicon -h

> @dpc-sdp/nuxt-ripple-cli@2.4.6 nuxt-ripple /Users/jason.smith/rep/ripple-framework/packages/nuxt-ripple-cli
> node ./dist/commands/index.js "favicon" "-h"

Usage: favicon [options]

Generate favicon assets

Options:
  -a, --apiKey <apiKey>        API key for the RealFaviconGenerator service
  -b, --baseUrl <baseUrl>      Tide API base url
  -i, --siteId <siteId>        Tide site ID
  -x, --extraPath <extraPath>  Extra path directory, this defaults to blank for production sites (default: "")
  -h, --help                   display help for command
```
- Use `-x` option if running in monorepo, e.g.
```
pnpm -F nuxt-ripple-cli nuxt-ripple favicon -a xxx -i 1287 -b https://master.content.vic.gov.au -x examples/nuxt-app
```

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-11-20 22:53 UTC, dylankelly approved these changes

2023-11-20 22:56 UTC, dylankelly requested changes

2023-11-20 22:56 UTC, dylankelly commented on packages/nuxt-ripple-cli/src/commands/favicon/favicon.ts
> +  const publicFolderPath = `${process.env.INIT_CWD}${
change this to `process.cwd()` instead and maybe have the ability to overwrite with an argument

2023-11-26 22:52 UTC, dylankelly approved these changes

2023-11-26 22:53 UTC, jeffdowdle approved these changes

2023-11-26 22:57 UTC, merged