feat(@dpc-sdp/nuxt-ripple): adds logging in vue/nuxt contexts
dpc-sdp/ripple-framework pull request #962
Opened 2023-12-13 02:33 UTC by jeffdowdle

**Issue**:

### What I did

- 
- 

### How to test

- 
- 

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2023-12-13 23:22 UTC, waitingallday approved these changes

2023-12-28 21:02 UTC, jeffdowdle commented on .gitignore
> -*.log*
@dylankelly I had to remove the trailing * from this otherwise it ignores the `00.logging.server.ts` file. Not sure if I've broken something by doing this though.

2023-12-28 22:58 UTC, lambry approved these changes

2024-01-08 22:38 UTC, dylankelly commented on packages/nuxt-ripple/composables/use-tide-page.ts
>          console.log('Cache reset for page', `page-${path}`)
we can remove this console log now

2024-01-08 22:39 UTC, dylankelly commented on packages/nuxt-ripple/composables/use-tide-page.ts
>        if (process.dev) {
Can we convert this console log to use debugLogger?

2024-01-08 22:42 UTC, dylankelly requested changes
couple of small things, otherwise it would be good to get this into 2.6 release

2024-01-12 04:17 UTC, dylankelly approved these changes

2024-01-12 04:38 UTC, merged