[R20-1184] native date picker
dpc-sdp/ripple-framework pull request #975
Opened 2024-01-01 23:27 UTC by lambry

**Issue**: https://digital-vic.atlassian.net/browse/R20-1184

### What I did

- Add basic native date input

### Checklist

#### For all PR's

- [ ] I've added relevant changes to the project Readme if needed.
- [ ] I've updated the documentation site as needed.
- [ ] I have added unit tests to cover my changes (if not applicable, please state why in a comment)

#### For new components only

- [ ] I have added a story covering all variants
- [ ] I have checked a11y tab in storybook passes
- [ ] Any events are emitted on the event bus

2024-01-01 23:49 UTC, dylankelly requested changes

2024-01-01 23:49 UTC, dylankelly commented on packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
> +        },
@lambry maybe leave this undocumented for now, we dont necessarily want everyone using it just yet

2024-01-02 04:11 UTC, lambry commented on packages/ripple-ui-forms/src/components/RplForm/RplForm.stories.mdx
> +        },
Thanks @dylankelly, that's removed now.

2024-01-02 04:59 UTC, dylankelly approved these changes

2024-01-02 04:59 UTC, merged